### ISSUE TITLE
d is not defined

### ISSUE THREAD

**Issue by 3ChiThai** [MrHeroBots/musicBot#2]
\main.js:93
                console.log(`(` + d.getHours() + `:` + d.getMinutes() + `)` + ` [` + a.username + `#` + a.discriminator + `] - failed - ` + msg.content + ` | ` + canUse);
                                  ^

ReferenceError: d is not defined

The problem is that d is defined in line 85. And is in IF Statement.
So I added 
let d = new Date(); 
In the 92 line

**Comment by Heroj04** [comment]
Fixed in 88f39a7
